name: Packages

on:
  repository_dispatch:
    branches:
      - main

  push:
    paths:
      - packages/core/**
      - packages/react/**

    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  packages: none
  deployments: write
  statuses: write

jobs:
  packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - name: Nx set SHAs
      uses: nrwl/nx-set-shas@v2.0.2

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Lint
      run: npx nx affected --target=lint --parallel=3

    - name: Test
      run: npx nx affected --target=test --parallel=3

    - name: Create Release Pull Request
      id: changesets
      uses: changesets/action@v1
      with:
        publish: npx nx affected --target=release --parallel=3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
